'use client';

import { Card } from '@/components/ui/card';
import { updateContent } from '@/lib/actions/content-actions';
import { getContentTemplates } from '@/lib/actions/sanity-actions';
import { generateSchema } from '@/lib/schemas';
import { ContentTemplateData, GenerateData } from '@/types/types';
import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast, Toaster } from 'sonner';
import z from 'zod';
import CardComponent from '../../../components/card';
import { Sparkle } from 'lucide-react';
import { FormComponent } from './form';
import useContentGeneration from '@/hooks/useContentGeneration';
import { GenerateActions } from '@/components/actions/generate-actions';
import { useQuery } from '@tanstack/react-query';
import { ContentType } from '@prisma/client';

export default function GenerateCard() {
  const [editedContent, setEditedContent] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const { data } = useQuery<ContentTemplateData>({
    queryKey: ['content-templates'],
    queryFn: () => getContentTemplates(),
  });

  const form = useForm<z.infer<typeof generateSchema>>({
    resolver: zodResolver(generateSchema),
    defaultValues: {
      id: '',
      templateSelector: 'none',
      topic: '',
      contentType: ContentType.BLOG_POST,
      tone: 'professional',
      context: '',
    },
  });

  const { savedContentId, generateContent, generatedContent } =
    useContentGeneration();

  const onSubmit = async (data: GenerateData) => {
    return await generateContent(data);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success('Content copied');
  };

  const handleEdit = () => {
    if (!isEditing) {
      setEditedContent(generatedContent);
    } else {
      setEditedContent('');
    }
    setIsEditing((prev) => !prev);
  };
  const handleSave = async () => {
    if (editedContent && editedContent !== generatedContent && savedContentId) {
      setIsSaving(true);
      setEditedContent(editedContent);
      try {
        await updateContent({
          contentId: savedContentId,
          editedContent: editedContent,
        });
        toast.success('Successfully updated content');
      } catch (error) {
        console.error(error);
        toast.error('Error during attempt to update content');
      } finally {
        setIsSaving(false);
      }
    }
  };

  return (
    <Card className="flex flex-col p-10 w-full justify-around md:flex-row">
      <div className={`${generatedContent ? 'flex-1' : 'w-1/2 mx-auto'}`}>
        <FormComponent
          form={form}
          onSubmit={onSubmit}
          templates={data?.templates}
        />
      </div>
      {generatedContent && (
        <div className="mt-4 p-4 border rounded flex-1 flex justify-center">
          <CardComponent
            data={{
              id: 0,
              icon: <Sparkle />,
              title: 'Generated Content:',
              description: 'Content generated by AI',
              content: editedContent || generatedContent,
              footer: '',
              action: (
                <GenerateActions
                  handleCopy={() => handleCopy(generatedContent)}
                  handleEdit={handleEdit}
                  handleSave={handleSave}
                  generatedContent={generatedContent}
                  editedContent={editedContent || generatedContent}
                  isEditing={isEditing}
                  isSaving={isSaving}
                />
              ),
            }}
            edit={isEditing}
            editedContent={editedContent || generatedContent}
            setEditedContent={setEditedContent}
          />
        </div>
      )}
      <Toaster position="top-center" />
    </Card>
  );
}
