'use client';

import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Spinner } from '@/components/ui/spinner';
import { Textarea } from '@/components/ui/textarea';
import { saveGeneratedContent, updateContent } from '@/lib/actions';
import { generateSchema } from '@/lib/schemas';
import { generatePromptText } from '@/lib/utils';
import { ContentType } from '@/prisma/app/generated/prisma/client/enums';
import { GenerateData } from '@/types/types';
import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { toast, Toaster } from 'sonner';
import z from 'zod';
import CardComponent from '../../../components/card';
import { Sparkle } from 'lucide-react';
import { FormComponent } from './form';
import useContentGeneration from '@/hooks/useContentGeneration';
import { WrapperCenter } from '@/components/wrapper-center';
import { GenerateActions } from '@/components/generate-actions';

export default function Generate() {
  const [editedContent, setEditedContent] = useState('');
  const [isEditing, setIsEditing] = useState(false);

  const form = useForm<z.infer<typeof generateSchema>>({
    resolver: zodResolver(generateSchema),
    defaultValues: {
      topic: '',
      contentType: ContentType.BLOG_POST,
      tone: 'professional',
      context: '',
    },
  });

  const { isGenerating, savedContentId, generateContent, generatedContent } =
    useContentGeneration();

  const onSubmit = async (data: GenerateData) => {
    return await generateContent(data);
  };

  const handleCopy = (text: string) => {
    navigator.clipboard.writeText(text);
    toast.success('Content copied');
  };

  const handleEdit = () => {
    if (!isEditing) {
      setEditedContent(generatedContent);
    } else {
      setEditedContent('');
    }
    setIsEditing((prev) => !prev);
  };
  const handleSave = async () => {
    if (editedContent && editedContent !== generatedContent && savedContentId) {
      setEditedContent(editedContent);
      try {
        await updateContent({
          contentId: savedContentId,
          editedContent: editedContent,
        });
        toast.success('Successfully updated content');
      } catch (error) {
        toast.error('Error during attempt to update content');
      }
    }
  };

  return (
    <Card className="flex flex-col p-10 w-full justify-around md:flex-row">
      <div className={`${generatedContent ? 'flex-1' : 'w-1/2 mx-auto'}`}>
        <FormComponent form={form} onSubmit={onSubmit} />
        {isGenerating && (
          <WrapperCenter>
            <Spinner className="size-10" />
          </WrapperCenter>
        )}
      </div>
      {generatedContent && (
        <div className="mt-4 p-4 border rounded flex-1 flex justify-center">
          <CardComponent
            data={{
              id: 0,
              icon: <Sparkle />,
              title: 'Generated Content:',
              description: 'Content generated by AI',
              content: editedContent || generatedContent,
              footer: '',
              action: (
                <GenerateActions
                  handleCopy={() => handleCopy(generatedContent)}
                  handleEdit={handleEdit}
                  handleSave={handleSave}
                  generatedContent={generatedContent}
                  editedContent={editedContent || generatedContent}
                  isEditing={isEditing}
                />
              ),
            }}
            edit={isEditing}
            editedContent={editedContent || generatedContent}
            setEditedContent={setEditedContent}
          />
        </div>
      )}
      <Toaster position="top-center" />
    </Card>
  );
}
