'use client';

import { Image as ImageType } from '@prisma/client';
import Image from 'next/image';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import useImageDelete from '@/hooks/useImageDelete';
import { Separator } from '@/components/ui/separator';
import DeleteContentDialog from '@/components/delete-content-dialog';

const empty = '---';

export const ImageDetails = ({ image }: { image: ImageType }) => {
  const { handleDelete, isDeleting, open, close, isOpen, deleteId, router } =
    useImageDelete();

  return (
    <section className="flex flex-col lg:flex-row gap-4">
      <div className="flex-1 lg:flex-[2]">
        <Image
          src={image?.url || ''}
          alt={image?.filename || 'empty file name'}
          width={image?.width || 300}
          height={image?.height || 300}
        />
      </div>
      <div className="flex-1 lg:flex-[1] flex flex-col gap-4 items-start">
        <Button onClick={() => router.push('/images')} className="w-full">
          Back to gallery
        </Button>
        <Separator className="my-5" />
        <Badge className="text-md">File name: {image?.filename}</Badge>
        <Badge className="text-md">
          Created at: {image?.createdAt.toLocaleDateString()}
        </Badge>
        <Badge className="text-md">Width: {image?.width}</Badge>
        <Badge className="text-md">Height: {image?.height}</Badge>
        <Badge className="text-md">
          Image type: {image?.mimeType.replace('image/', '').toUpperCase()}
        </Badge>
        <Badge className="text-md">
          Generated by AI: {image?.isGenerated ? 'Yes' : 'No'}
        </Badge>
        <Badge className="text-md" variant="outline">
          AI model: {image?.model || empty}
        </Badge>
        <Badge className="text-md" variant="outline">
          AI image quality: {image?.quality ?? empty}
        </Badge>
        <Badge className="text-md" variant="outline">
          AI image style: {image?.style || empty}
        </Badge>
        <Separator className="my-5" />
        <Button
          variant="destructive"
          onClick={() => open(image?.id as string)}
          disabled={isDeleting}
          className="w-full"
        >
          Delete
        </Button>
      </div>

      {isOpen && (
        <DeleteContentDialog
          open={isOpen}
          onClose={close}
          onConfirm={() => handleDelete(deleteId as string)}
          deleteContentTypeId={deleteId}
          contentType="image"
        />
      )}
    </section>
  );
};
