'use client';

import { Card } from '@/components/ui/card';
import { getContentImages } from '@/lib/actions/image-actions';
import { generateImageSchema } from '@/lib/schemas';
import { ImageContentData, ImageSize } from '@/types/types';
import { zodResolver } from '@hookform/resolvers/zod';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { toast, Toaster } from 'sonner';
import z from 'zod';
import { FormComponent } from './form';
import { WrapperCenter } from '@/components/wrapper-center';
import { Spinner } from '@/components/ui/spinner';
import { useState } from 'react';
import { useSession } from 'next-auth/react';
import CardComponent from '@/components/card';
import { Sparkle } from 'lucide-react';
import type { Image } from '@prisma/client';
import { GenerateImageActions } from '@/components/actions/generate-image-actions';
import { exportAsImage } from '@/lib/utils';

export default function GenerateImage() {
  const session = useSession();
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedImage, setGeneratedImage] = useState<Image | null>(null);
  const { data } = useQuery<ImageContentData>({
    queryKey: ['content-templates'],
    queryFn: () => getContentImages(session?.data?.user?.id as string),
  });

  const form = useForm<z.infer<typeof generateImageSchema>>({
    resolver: zodResolver(generateImageSchema),
    defaultValues: {
      prompt: '',
      quality: 'standard',
      size: '1024x1024',
      style: 'vivid',
    },
  });

  const onSubmit = async (data: z.infer<typeof generateImageSchema>) => {
    try {
      setIsGenerating(true);
      const response = await fetch('/api/auth/generate/image', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        toast.error('Error during sending query to AI');
        return;
      }

      const result = await response.json();

      setGeneratedImage(result.image);
      toast.success('Image generation successfully');
    } catch (error) {
      setIsGenerating(false);
      console.error(error);
      toast.error('Error during sending query to AI');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSave = () => {
    toast.success('Image saved to your library!');
  };

  const handleRegenerate = () => {
    if (!generatedImage) return;

    form.reset({
      prompt: generatedImage.prompt || '',
      quality: generatedImage.quality || '1024x1024',
      size:
        (`${generatedImage.width}x${generatedImage.height}` as ImageSize) ||
        'auto',
      style: generatedImage.style || 'vivid',
    });

    toast.info('Form updated with previous settings. Modify and regenerate!');
  };

  return (
    <Card className="flex flex-col p-10 w-full justify-around md:flex-row">
      <div className={`${data?.images ? 'flex-1' : 'w-1/2 mx-auto'}`}>
        <FormComponent form={form} onSubmit={onSubmit} />
        {isGenerating && (
          <WrapperCenter>
            <Spinner className="size-10" />
          </WrapperCenter>
        )}
      </div>
      {generatedImage && (
        <div className="mt-4 p-4 border rounded flex-1 flex justify-center">
          <CardComponent
            data={{
              id: 0,
              icon: <Sparkle />,
              title: 'Image Generation:',
              description: 'Image generated by AI',
              content: generatedImage,
              footer: '',
              action: (
                <GenerateImageActions
                  handleDownload={() => exportAsImage(generatedImage)}
                  handleSave={handleSave}
                  handleRegenerate={handleRegenerate}
                />
              ),
            }}
          />
        </div>
      )}
      <Toaster position="top-center" />
    </Card>
  );
}
